services:
    eureka-server:
      build: .
      image: eureka-server-image
      ports:
        - "8761:8761"
      networks:
        - pubnetwork

    api-gateway-app:
      image: api-gateway-image
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
      ports:
        - "8080:8080"
      networks:
        - pubnetwork

    customer-app:
      image: customer-service-image
      environment:
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
          - DATABASE_URL=jdbc:postgresql://postgres_db:5432/postgres
          - DATABASE_USERNAME=postgres
          - DATABASE_PASSWORD=postgres
      ports:
        - "8002:8002"
      networks:
        - pubnetwork
      depends_on:
        - postgres_db

    postgres_db:
      image: postgres:latest
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      networks:
        - pubnetwork


    order-service:
      image: order-service-image
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      ports:
        - "8004:8004"
      networks:
        - pubnetwork
      depends_on:
        - mongo_db

    mongo_db:
      image: mongo:latest
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: mongo_db
      networks:
        - pubnetwork

networks:
  pubnetwork:



