version: "5"
services:
  pubmongo:
    image: mongo:latest
    container_name: "pub-mongo-container"
    ports:
      - 27017:27017

  order-microservice-image :
    image: order-microservice-image:latest
    container_name: "order-microservice-container"
    ports:
      - 8004:8004

    links:
      - pubmongo